language: python
python:
  - "2.6"
  - "2.7"
services:
  - mongodb
  - redis-server

# command to install dependencies
install: 
  - pip install pymongo
  - pip install tornado
  - pip install redis
  - pip install docopt
# command to run tests
script: 
  - python setup.py install
  - cd turbo/test
  - python -m runtests