language: python
python:
  - "2.6"
  - "2.7"
services:
  - mongodb
  - redis-server

# command to install dependencies
install: 
  - pip install pymongo
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then travis_retry pip install 'tornado<=4.3.0' unittest2; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then travis_retry pip install tornado; fi
  - pip install redis
  - pip install docopt
# command to run tests
script: 
  - python setup.py install
  - cd turbo/test
  - python -m unittest -v runtests.main
