site_name: turbo
pages:
- [index.md, Home]
- [intro.md, Introduction]
- [quickstart.md, Quickstart]
- [tutorial/index.md, Tutorial]
- [tutorial/helper.md, 'Tutorial', 'helper']
- [tutorial/model.md, 'Tutorial', 'model']
- [tutorial/db.md, 'Tutorial', 'db']

theme: readthedocs
